name: 'Trabalho Final Integração Contínua - N1 Execução Manual'

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonando repositório
        uses: actions/checkout@v4

      - name: 📦 Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: 📦 Instalando dependências
        run: yarn

      - name: 🧪 Executando Testes Unitários
        run: npm test
